### ISSUE TITLE
php7.1 编译失败

### ISSUE THREAD

**Issue by zuozhehao** [msgpack/msgpack-php#114]
msgpack-php-master/msgpack.c:160:29: error: variable has incomplete type 'msgpack_unserialize_data_t' (aka 'struct php_unserialize_data')
        msgpack_unserialize_data_t var_hash;
                                   ^
/usr/include/php/ext/standard/basic_functions.h:213:10: note: forward declaration of 'struct php_unserialize_data'
                struct php_unserialize_data *data;
                       ^
/msgpack-php-master/msgpack.c:210:29: error: variable has incomplete type 'msgpack_unserialize_data_t' (aka 'struct php_unserialize_data')
        msgpack_unserialize_data_t var_hash;
                                   ^
/usr/include/php/ext/standard/basic_functions.h:213:10: note: forward declaration of 'struct php_unserialize_data'
                struct php_unserialize_data *data;

**Comment by km3945** [comment]
/root/msgpack-php/msgpack.c: In function ?.s_srlzr_decode_msgpack?.
/root/msgpack-php/msgpack.c:160:29: error: storage size of ?.ar_hash?.isn?. known
  msgpack_unserialize_data_t var_hash;
                             ^
/root/msgpack-php/msgpack.c: In function ?.hp_msgpack_unserialize?.
/root/msgpack-php/msgpack.c:210:29: error: storage size of ?.ar_hash?.isn?. known
  msgpack_unserialize_data_t var_hash;

**Comment by thedotedge** [comment]
Same problem with 7.1:

```
cc -I. -I/private/tmp/pear/temp/msgpack -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-rootjVYNDH/msgpack-2.0.1/include -I/private/tmp/pear/temp/pear-build-rootjVYNDH/msgpack-2.0.1/main -I/private/tmp/pear/temp/msgpack -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/msgpack/msgpack.c  -fno-common -DPIC -o .libs/msgpack.o
/private/tmp/pear/temp/msgpack/msgpack.c:160:29: error: variable has incomplete type 'msgpack_unserialize_data_t' (aka 'struct php_unserialize_data')
        msgpack_unserialize_data_t var_hash;
                                   ^
/usr/local/php5/include/php/ext/standard/basic_functions.h:213:10: note: forward declaration of 'struct php_unserialize_data'
                struct php_unserialize_data *data;
                       ^
/private/tmp/pear/temp/msgpack/msgpack.c:210:29: error: variable has incomplete type 'msgpack_unserialize_data_t' (aka 'struct php_unserialize_data')
        msgpack_unserialize_data_t var_hash;
                                   ^
/usr/local/php5/include/php/ext/standard/basic_functions.h:213:10: note: forward declaration of 'struct php_unserialize_data'
                struct php_unserialize_data *data;
```

**Comment by Sean-Der** [comment]
Hey everyone!

@sodabrew fixed this with https://github.com/msgpack/msgpack-php/commit/709b68a6974f334b902e1b9037b4000ad1c3f41c would you mind trying with master again? Feel free to reopen if you are still having issues
