### ISSUE TITLE
php warning [msgpack] (php_msgpack_unserialize) extra bytes in

### ISSUE THREAD

**Issue by lgang06** [msgpack/msgpack-php#122]
使用lua的msgpack在nginx直接返回后，在php内部使用msgpack_unpack ()解析会出现php warning [msgpack] (php_msgpack_unserialize) extra bytes in的错误提示，数据解析正常，请问如何解决这个错误提示
版本说明：
lua：5.1.4
lua-msgpack：0.5.0
php：7.0.12
php-msgpack:2.0.2

**Comment by joshua317** [comment]
how do solve it?
