### ISSUE TITLE
Unable to compile with PHP 7.4.0 on macOS 10.15.1

### ISSUE THREAD

**Issue by panosru** [msgpack/msgpack-php#141]
I tried with both pecl and manual compile, both ended up with the same error:
![image](https://user-images.githubusercontent.com/400362/70038912-b5baa180-15c1-11ea-808d-30aa7bdec052.png)
I'm on macOS 10.15.1

**Comment by rybakit** [comment]
It works on Linux: https://travis-ci.org/tarantool-php/client/jobs/619782342#L158-L160

**Comment by panosru** [comment]
Indeed, it seems to be working on Linux; thus I changed the title of the topic accordingly

**Comment by panosru** [comment]
Could anyone at least point me on where to look to solve that issue? I can see based on the errors that it does not recognise the zend types (or something related to zend), does that means that the compiler may be missing some paths? Should I try addition some paths before compiling that might solve the issue?

Thanks!

**Comment by nagaho** [comment]
It works on macOS and php-7.4.

```diff
diff --git a/msgpack_convert.c b/msgpack_convert.c
index b1d4334..2fdafa1 100644
--- a/msgpack_convert.c
+++ b/msgpack_convert.c
@@ -11,7 +11,7 @@ static inline int msgpack_convert_long_to_properties(HashTable *ht, zval *object
     if (props != NULL) {
         zval *data, tplval, *dataval, prop_key_zv;
         zend_string *prop_key;
-        ulong prop_key_index;
+        zend_ulong prop_key_index;
         const char *class_name, *prop_name;
         size_t prop_len;

@@ -102,7 +102,7 @@ static inline int msgpack_convert_string_to_properties(zval *object, zend_string
 int msgpack_convert_array(zval *return_value, zval *tpl, zval *value) /* {{{ */ {
     zend_string *key;
     int key_type;
-    ulong key_index;
+    zend_ulong key_index;
     zval *data;
     HashTable *ht, *htval;

@@ -329,7 +329,7 @@ int msgpack_convert_object(zval *return_value, zval *tpl, zval *value) /* {{{ */
             HashTable *ht, *ret, *var = NULL;
             zend_string *str_key;
             zval *data;
-            ulong num_key;
+            zend_ulong num_key;

             ht = HASH_OF(value);
             ret = HASH_OF(return_value);
```

**Comment by panosru** [comment]
@nagaho yup! Now it works! Thanks!

**Comment by cmb69** [comment]
This affects Windows as well, and is caused by https://github.com/php/php-src/commit/bebcdcc74573b015c22238dbc9b2698c88b7a601. I suggest to re-open this ticket.
