### ISSUE TITLE
try to compile from source by zts-phpize

### ISSUE THREAD

**Issue by ooghry** [msgpack/msgpack-php#150]
Hello
As you can see in my gist: [zts-php 7.2 msgpack 2.1.0](https://gist.github.com/ooghry/024448c1a7d5acea4a9ad06d66519371)
I try use msgpack in zts mode,almost every things is ok but module could not load with this error message:
`msgpack.so: undefined symbol: ps_globals`

no problem with non-zts php.

**Comment by m6w6** [comment]
Hi! You need to point `configure` to the ZTS `php-config`, e.g. `./configure --with-php-config=/path/to/zts-php/bin/php-config` 

HTH

**Comment by ooghry** [comment]
It works,Thank you.
