### ISSUE TITLE
php_add_session_var: symbol not found

### ISSUE THREAD

**Issue by swc123456** [msgpack/msgpack-php#151]
PHP Warning:  PHP Startup: Unable to load dynamic library 'msgpack.so' (tried: /usr/lib/php7/modules/msgpack.so (Error relocating /usr/lib/php7/modules/msgpack.so: php_add_session_var: symbol not found), /usr/lib/php7/modules/msgpack.so.so (Error loading shared library /usr/lib/php7/modules/msgpack.so.so: No such file or directory)) in Unknown on line 0
PHP 7.2.26 (cli) (built: Dec 22 2019 06:01:52) ( NTS )

**Comment by m6w6** [comment]
Did you by any chance disable session support?
