### ISSUE TITLE
MsgPack TS non TS fail

### ISSUE THREAD

**Issue by DevHeaven** [msgpack/msgpack-php#167]
Hello

I know this isn't a support forum but I'm at the end, can't seem to find a solution no matter what I try.

I've tried setting up MsgPack on my local machine (Windows 10 , PHP 8.1.9)
I've downloaded multiple versions of the DLL from https://pecl.php.net/package/msgpack/2.1.2/windows 

But no matter which I try (TS, no-TS, x86 , x64 ...) I always get an error trying to execute a PHP script.

`PHP Warning:  PHP Startup: Unable to load dynamic library 'php_msgpack.dll' (tried: ext\php_msgpack.dll (The specified module could not be found), ext\php_php_msgpack.dll.dll (The specified module could not be found)) in Unknown on line 0`

If there's anybody with a golden tip, I'd appreciate it soo much!

**Comment by DevHeaven** [comment]
@m6w6  Thank you nonetheless for your response ! 

The filename is correct, and it is in the /ext folder.
I load several other extensions like rdkafka etcetera which work fine.
All extensions are in my C:\PHP8\EXT folder

I would expect such a message when trying a non compatible dll for the specific OS and version , but this doesn't seem to be the case here.

**Comment by DevHeaven** [comment]
PS : when trying the latest PHP 8. version for Threadsafe X64 (which is my machine version of PHP) I get a dialogue error

**The procedure entry point zval_get_long_func@88 could not be located in the dynamic link library**

**Comment by m6w6** [comment]
Not sure, but reading your initial comment again, I noticed you're running 8.1 and probably downloaded the extension for 8.0.

Try the 8.1 from here: https://windows.php.net/downloads/pecl/releases/msgpack/2.2.0rc1/

**Comment by DevHeaven** [comment]
😱 how could I have missed that .... *walks the walk of shame*

Thanks so much !!!! 👍
