### ISSUE TITLE
Compilation error reported

### ISSUE THREAD

**Issue by anehqiaoxia** [msgpack/msgpack-php#168]
ck/msgpack_pack.c  -fPIC -DPIC -o .libs/msgpack_pack.o
In file included from /tmp/pear/temp/msgpack/msgpack_pack.c:4:
In function ‘smart_str_appendl_ex’,
    inlined from ‘msgpack_pack_long’ at /tmp/pear/temp/msgpack/msgpack/pack_template.h:468:5:
/usr/include/php/20190902/Zend/zend_smart_str.h:121:2: warning: writing 2 bytes into a region of size 1 [-Wstringop-overflow=]
  121 |  memcpy(ZSTR_VAL(dest->s) + ZSTR_LEN(dest->s), str, len);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘smart_str_appendl_ex’,
    inlined from ‘msgpack_pack_long’ at /tmp/pear/temp/msgpack/msgpack/pack_template.h:468:5:
/usr/include/php/20190902/Zend/zend_smart_str.h:121:2: warning: writing 2 bytes into a region of size 1 [-Wstringop-overflow=]
  121 |  memcpy(ZSTR_VAL(dest->s) + ZSTR_LEN(dest->s), str, len);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘smart_str_appendl_ex’,
    inlined from ‘msgpack_pack_str’ at /tmp/pear/temp/msgpack/msgpack/pack_template.h:763:9:
/usr/include/php/20190902/Zend/zend_smart_str.h:121:2: warning: writing 2 bytes into a region of size 1 [-Wstringop-overflow=]
  121 |  memcpy(ZSTR_VAL(dest->s) + ZSTR_LEN(dest->s), str, len);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Jan-E** [comment]
For PHP 7.4 you neeed to use release 2.1.1 
https://github.com/msgpack/msgpack-php/releases/tag/msgpack-2.1.1

**Comment by m6w6** [comment]
Huh? These are warnings?

**Comment by Jan-E** [comment]
Right. I did not notice that yet,
