### ISSUE TITLE
a PHP Warning

### ISSUE THREAD

**Issue by rryqszq4** [msgpack/msgpack-php#41]
when i call msgpack_unpack function ,  i got a PHP Warning .
"PHP Warning:  msgpack   php_msgpack_unserialize  Extra bytes in..."

but i used msgpack-c to serialize and msgpack-php to deserialize.

my environment : 
php-5.3.27
msgpack-c-cpp-0.5.9 
msgpack-0.5.5 +

gg

**Comment by laruence** [comment]
could you show me the reproduce case?

I mean the target bin data.... 

thanks

**Comment by rryqszq4** [comment]
string(1024) "??hello?messagepack"
lenght must be 19 ,but is 1024.

msgpack_unpack result is right~
array(2) {
  [0]=>
  string(5) "hello"
  [1]=>
  string(11) "messagepack"
}

**Comment by Sean-Der** [comment]
Hi @rryqszq4 !

Some information was lost because some of the things in $data pre unpack are not printable. Would you mind re-doing this except with this sample code instead?

```php
<?php
...
$data = '';
while(true){
    $out = @socket_read($socket, 1024, PHP_NORMAL_READ);
    if ($out === false){echo "stop;";break;}
    $data.=$out;
}
var_dump(bin2hex($data));
...
```

**Comment by Sean-Der** [comment]
Feel free to reopen @rryqszq4 when you have a test case.

thanks!
