### ISSUE TITLE
session serialize handler adds a null key

### ISSUE THREAD

**Issue by golgote** [msgpack/msgpack-php#50]
I am using the msgpack session serialize handler in latest release from pecl (0.5.6). I tested this with both file and redis save handlers.

Here is the php array that is serialized in the session : 
array(1) { ["acl_user"]=> array(2) { ["id"]=> string(10) "NGwnGUqwsr" ["status"]=> int(2) } }

Here is the result I expect (without ws added for readability...) : 
```
               \x81 \xa8 acl_user \x82     \xa2 id   \xaa NGwnGUqwsr   \xa6 status \x02
```

Here is the result I get : 
```
\x82     \xc0 \x01  \xa8 acl_user \x82     \xa2 id   \xaa NGwnGUqwsr   \xa6 status \x02
```

It looks like there is a null indexed value of 1 added before getting to the expected array (I am no expert in msgpack decoding, so I might be wrong...).

This null indexed value makes it impossible to share session with other tools (like Lua in Redis for example) because null (or nil) cannot be used as a key to index a value.

Is it possible to get rid of this null indexed value that seems useless ?

**Comment by golgote** [comment]
I forgot to mention that I am running PHP 5.6.6.
Thanks.

**Comment by joeyhub** [comment]
A five second scan and here is something dodgy already:
  zend_hash_internal_pointer_reset_ex(htval, &valpos);
            for (;; zend_hash_move_forward_ex(htval, &valpos))

I never looked closely, but it's guess that's it.

**Comment by joeyhub** [comment]
# php -r 'echo msgpack_pack(["acl_user" => ["id"=>"NGwnGUqwsr","status"=>2]]);' | xxd
    0000000: 81a8 6163 6c5f 7573 6572 82a2 6964 aa4e  ..acl_user..id.N
    0000010: 4777 6e47 5571 7773 72a6 7374 6174 7573  GwnGUqwsr.status
    0000020: 02                                       .

    # php -dsession.serialize_handler=msgpack -r 'session_start();$_SESSION=["acl_user" => ["id"=>"NGwnGUqwsr","status"=>2]]; echo session_encode();session_destroy();' | xxd
    0000000: 82c0 01a8 6163 6c5f 7573 6572 82a2 6964  ....acl_user..id
    0000010: aa4e 4777 6e47 5571 7773 72a6 7374 6174  .NGwnGUqwsr.stat
    0000020: 7573 02                                  us.

It's specific to sessions and in php 5.4.

**Comment by Sean-Der** [comment]
Hey @golgote @joeyhub 

So, this comes down to the fact that [http_session_vars](https://github.com/msgpack/msgpack-php/blob/master/msgpack.c#L159) is a reference. 

Later when this array is [packed](https://github.com/msgpack/msgpack-php/blob/master/msgpack_pack.c#L307) we pack the reference appropriately .

Since you are just passing these values to redis, and you don't need the ref 'extension type' you could/should(?) just use `ini_set('msgpack.php_only', 0);`

I made the following test case to confirm this behavior. Flip msgpack.php_only to see the changes.

```
ini_set('session.serialize_handler', 'msgpack');
ini_set('msgpack.php_only', 0);

$input = [
    "acl_user" => [
        "id"=>"NGwnGUqwsr",
        "status"=>2
    ]
];


$std_serialize = msgpack_pack($input);

session_start();
$_SESSION = $input;
$session_serialize = session_encode();
session_destroy();

echo $std_serialize === $session_serialize ? 'OK' : 'ERROR', PHP_EOL;
echo bin2hex($std_serialize), PHP_EOL;
echo bin2hex($session_serialize), PHP_EOL;
```

I *think* this is a WONTFIX @laruence opinions?
