### ISSUE TITLE
Add code coverage support

### ISSUE THREAD

**Issue by Sean-Der** [msgpack/msgpack-php#54]
Hey @laruence 
I [ported](https://github.com/Sean-Der/pecl-mail-mailparse/tree/php7) mailparse, and when adding travis-ci support I also looked into beefing up the tests. After I got gcov working I decided to expand and get it online.

 Install the [codecov extension](https://github.com/codecov/browser-extension) and then open [mailparse.c](https://github.com/Sean-Der/pecl-mail-mailparse/blob/php7/mailparse.c) I now get built into github coverage per file from the test suite, it is really helping me write more comprehensive tests. Also here is the [.travis.yml](https://github.com/Sean-Der/pecl-mail-mailparse/blob/php7/.travis.yml)

* You think this is worth adding to msgpack?
* You think this is something worth adding to every PHP extension that is on GitHub? How could I tell people to check this out?

**Comment by laruence** [comment]
it's okey to add to msgpack, but not sure for other extensions..  since they are not ours :)

anyway, for PHP, we already have gcov.php.net...

**Comment by Sean-Der** [comment]
Is there anyway we could use gcov.php.net?

For now this is closed by fe72ef7315b672a9658bc980112bb5f501ae6f1a you can see the coverage results at [here](https://codecov.io/github/msgpack/msgpack-php) you can also install the [codecov extension](https://github.com/codecov/browser-extension) and see the results actually in github. I will try and look for places where code coverage is missing.

thanks!
