### ISSUE TITLE
when will msgpack php v5 version be released?

### ISSUE THREAD

**Issue by zhangbiao2009** [msgpack/msgpack-php#55]
I'd like to know when msppack php v5 version will be released, we have a project rely on this. Thanks!

**Comment by methane** [comment]
There are no "v5".
There are "old" and "current" spec.

**Comment by Sean-Der** [comment]
Hey @zhangbiao2009 

Currently master fully supports v5/current, so building from source should work great!

However, I don't know when a release will be done that is up to @laruence I don't have access.

**Comment by zhangbiao2009** [comment]
@Sean-Der thank you very much!

**Comment by lvht** [comment]
Hi, @Sean-Der , could you just make a tag, so we could download by the new tag. Thanks.

**Comment by laruence** [comment]
sorry for the delay, it was released at pecl.php.net/msgpack

**Comment by docteurklein** [comment]
awesome! thanks
