### ISSUE TITLE
Release a new version to support msgpack 2.0

### ISSUE THREAD

**Issue by lvht** [msgpack/msgpack-php#56]
The latest version 0.5.6 released in the http://pcel.php.net has no support for msgpack 2.0 which has been supported (or partial?) by the master branch. I think it would be a convenience to deploy a new version to the http://pcel.php.net.

Thanks.

**Comment by Sean-Der** [comment]
Hi @lvht !
msgpack 2.0 should be fully supported by the master branch. If you are having problems please open an issue, will try to get to it right away.

Issue #55 is open for this, everything is ready but I don't have the permissions to release a new version. When @laruence gets a chance we will release right away.

thanks!
