### ISSUE TITLE
Use as xcopy-deployable folders?

### ISSUE THREAD

**Issue by UweKeim** [msgpack/msgpack-php#62]
Is there any chance to use msgpack-php _without_ installing it through PECL?

I want to deliver my project as a standalone folder without depending on any other server configuration beside PHP being installed.

[This answer on SO claims that it is possible](http://stackoverflow.com/a/2960223/107625) but I want to directly ask here for your specific package.

**So my question is:**

(How) can I ship msgpack-php as a sub folder of my website without installing it on the server?

**Comment by Sean-Der** [comment]
Hey @UweKeim 

msgpack-php is a module, so it will have to be compiled. If you know the target environment you could include the `msgpack.so` and you only have to compile it once per environment. 

Could you include msgpack-php is a submodule, and then compile it on the target host? You will need the PHP headers + a C compiler, but that means you at least will not need root access (to install it) you can then just have your PHP script include the module.

There are a bunch of ways to solve this problem, but the short answer is no. If you are doing a wide release and don't know all the target environments there is not going to be a way to do this without having the end user compile/install the module.

**Comment by UweKeim** [comment]
Thanks a lot, @Sean-Der — that's what I feared to hear :wink: 

Maybe someone someday will implement a pure-PHP solution, without any dependencies, even if it is a bit slower than the current C implementation.

(Just like e.g. [this pure-PHP ZIP implementation](http://www.phpconcept.net/pclzip/))

Thanks again for your fast reply.

**Comment by rybakit** [comment]
@UweKeim There is already a [number of pure php implementations](https://github.com/search?utf8=%E2%9C%93&q=msgpack+php&type=Repositories&ref=searchresults) available (I also created one by myself, but didn't opensource it yet).

**Comment by UweKeim** [comment]
Awesome! Thanks a log, @rybakit!

**Comment by rybakit** [comment]
@UweKeim If you still have interest in a pure php library, take a look at [msgpack.php](https://github.com/rybakit/msgpack.php) which I've just released.

**Comment by UweKeim** [comment]
Thank you very much, @rybakit
