### ISSUE TITLE
Wierd var_dump() output for unserialized objects

### ISSUE THREAD

**Issue by rybakit** [msgpack/msgpack-php#64]
Is there a reason to dump unserialized objects to such a [specific format](https://github.com/msgpack/msgpack-php/blob/master/tests/012.phpt#L44-L51)?

``` php
object(Obj)#%d (3) {
  ["a"]=>
  int(1)
  [%r"?b"?:protected"?%r]=>
  int(2)
  [%r"?c"?:("Obj":)?private"?%r]=>
  int(3)
}
```

To compare, here is a standard `var_dump()` output for the same object (https://3v4l.org/nXGBP):

``` php
object(Obj)#1 (3) { 
  ["a"]=> 
  int(1) 
  ["b":protected]=> 
  int(2) 
  ["c":"Obj":private]=> 
  int(3) 
}
```

**Comment by Sean-Der** [comment]
Hi @rybakit 

Is this in PHP 5 (and also is the behavior different in PHP 7)?

I think this is because we use the symtable operations, instead of the properties API? This wouldn't be hard to fix

**Comment by rybakit** [comment]
Looks like this is only the case for PHP 5 (https://travis-ci.org/rybakit/travis-sandbox#L228-L235). It would be great to bring it in line with standard PHP output ;)

**Comment by Sean-Der** [comment]
Yea totally! I agree it should be fixed.

I have a little bit of time this weekend, and will try my best to get it done then! If by Monday it isn't done feel free to poke me via GitHub/email and I will work on it right away.

thanks!

**Comment by rybakit** [comment]
Great! Thank you very much for looking into it and the quick responses!

**Comment by rybakit** [comment]
Hey @Sean-Der 
Have you had a chance to look into the issue yet?

**Comment by Sean-Der** [comment]
Hey @rybakit!

Sorry I got sick/burned out, so have been doing the bare minimum amount of work the past couple of days!

Sorry for the silence, this is still on my TODO list!

**Comment by rybakit** [comment]
No worries and get better!

**Comment by m6w6** [comment]
This is expected, %r encloses regexes in tests' EXPECTF sections.
