### ISSUE TITLE
Integer overflow on a 64-bit system

### ISSUE THREAD

**Issue by rybakit** [msgpack/msgpack-php#67]
Unpacking 64-bit unsigned integer will result in a negative value if the value is bigger than 2^63 (as PHP does not support unsigned integers):

``` php
php > var_dump(msgpack_unpack("\xcf"."\xff\xff\xff\xff"."\xff\xff\xff\xff"));
int(-1)
```

But [PHP's behavior](http://php.net/manual/en/language.types.integer.php#language.types.integer.overflow) in such cases is to fall back to `float/double`:

> If PHP encounters a number beyond the bounds of the integer type, it will be interpreted as a float instead. Also, an operation which results in a number beyond the bounds of the integer type will return a float instead. 

``` php
php > var_dump(PHP_INT_MAX + 1);
double(9.2233720368548E+18)
php > var_dump(hexdec('ffffffff'.'ffffffff'));
double(1.844674407371E+19)
```

I wonder if it would be reasonable to get `msgpack_unpack()` in line with PHP engine? Or return a string representation of the value?

**Comment by rybakit** [comment]
For the record, [json_decode()](http://php.net/manual/en/function.json-decode.php#refsect1-function.json-decode-parameters) by default casts uint32 values to float. And provider the `JSON_BIGINT_AS_STRING` option to cast them to strings.

**Comment by andypost** [comment]
Got an issue with passing this test on 32-bits (x86) and PHP 7.4.8
```
msgpack-2.1.1/tests$ cat issue067.diff 
001+ string(19) "9223372036854775807"
001- int(9223372036854775807)
```

**Comment by andypost** [comment]
Any suggestion how to fix running this test?

**Comment by m6w6** [comment]
This test should probably not be run on x32, or be duplicated for x32 to test for the correct output.
