### ISSUE TITLE
[PHP] From libmsgpack.a to .so

### ISSUE THREAD

**Issue by pepperav** [msgpack/msgpack-php#70]
Hi,
I need to compile for powerpc platform and I need a shared object file.

If I compile using
<pre>./configure CC=powerpc-e300c3-linux-gnu-gcc --host=powerpc</pre>

I have two files:
* _libmsgpack.a_
* _msgpack.la_

How can I include this file into php?

**Comment by Sean-Der** [comment]
Hi @pepperav 

Sorry I am not able to answer this, since it is not msgpack-php related (and I have no experience cross-compiling PHP extensions) Wish I could help!

Have you tried emailing the PHP mailing lists? You might be able to get more help there.
