### ISSUE TITLE
PHP Warning:  [msgpack] (php_msgpack_unserialize) Parse error in

### ISSUE THREAD

**Issue by ecyuan** [msgpack/msgpack-php#71]
Why throw this error, in some condition is ok, but other get this error: <br/>
PHP Warning:  [msgpack] (php_msgpack_unserialize) Parse error in;</br>

try this code:

php -c /etc/php5/fpm/php.ini -r "var_dump(msgpack_unserialize(base64_decode('3AAdrGFvanBxMjNCcDVlaNkkYzgxZmJlNjAtMzg4NC00ZWZlLWFlZjQtNjZlOGEzMzcwYWNlrzY5MTEwODI2MDY3OTU2M7E2QTo2MzpBRTpEQTo0Mzo1MKCgsjY4MTU0OTI2MTgyMDY2MTc2MKCgoKCgoAGiREWgoKCgoKCm5YW25LuWoM5WMyPDoKCgoKJlbg==')));"

I use python to do same unpack, it success!

>>> msgpack.unpackb(base64.b64decode('3AAdrGFvanBxMjNCcDVlaNkkYzgxZmJlNjAtMzg4NC00ZWZlLWFlZjQtNjZlOGEzMzcwYWNlrzY5MTEwODI2MDY3OTU2M7E2QTo2MzpBRTpEQTo0Mzo1MKCgsjY4MTU0OTI2MTgyMDY2MTc2MKCgoKCgoAGiREWgoKCgoKCm5YW25LuWoM5WMyPDoKCgoKJlbg=='))
['aojpq23Bp5eh', 'c81fbe60-3884-4efe-aef4-66e8a3370ace', '691108260679563', '6A:63:AE:DA:43:50', '', '', '681549261820661760', '', '', '', '', '', '', 1, 'DE', '', '', '', '', '', '', '\xe5\x85\xb6\xe4\xbb\x96', '', 1446192067, '', '', '', '', 'en']

**Comment by rybakit** [comment]
It works for me without any error or warning.
PHP 5.5.9, msgpack 0.5.6 beta

**Comment by ecyuan** [comment]
My env is :  msgpack 0.5.6-dev.    PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)

**Comment by Sean-Der** [comment]
Hi @ecyuan!

Thanks for using mspack, sorry to say I am getting the same results as @rybakit 

```
var_dump(msgpack_unserialize(base64_decode('3AAdrGFvanBxMjNCcDVlaNkkYzgxZmJlNjAtMzg4NC00ZWZlLWFlZjQtNjZlOGEzMzcwYWNlrzY5MTEwODI2MDY3OTU2M7E2QTo2MzpBRTpEQTo0Mzo1MKCgsjY4MTU0OTI2MTgyMDY2MTc2MKCgoKCgoAGiREWgoKCgoKCm5YW25LuWoM5WMyPDoKCgoKJlbg==')));

```

Gives me

```
array(29) {
  [0]=>
  string(12) "aojpq23Bp5eh"
  [1]=>
  string(36) "c81fbe60-3884-4efe-aef4-66e8a3370ace"
  [2]=>
  string(15) "691108260679563"
  [3]=>
  string(17) "6A:63:AE:DA:43:50"
  [4]=>
  string(0) ""
  [5]=>
  string(0) ""
  [6]=>
  string(18) "681549261820661760"
  [7]=>
  string(0) ""
  [8]=>
  string(0) ""
  [9]=>
  string(0) ""
  [10]=>
  string(0) ""
  [11]=>
  string(0) ""
  [12]=>
  string(0) ""
  [13]=>
  int(1)
  [14]=>
  string(2) "DE"
  [15]=>
  string(0) ""
  [16]=>
  string(0) ""
  [17]=>
  string(0) ""
  [18]=>
  string(0) ""
  [19]=>
  string(0) ""
  [20]=>
  string(0) ""
  [21]=>
  string(6) "其他"
  [22]=>
  string(0) ""
  [23]=>
  int(1446192067)
  [24]=>
  string(0) ""
  [25]=>
  string(0) ""
  [26]=>
  string(0) ""
  [27]=>
  string(0) ""
  [28]=>
  string(2) "en"
}
```

I am using `PHP 5.5.31-dev (cli) (built: Oct 22 2015 16:26:18) (DEBUG)`

With a msgpack built from the current HEAD of the master branch `105961a93599a5a12f2e33eaebe7b25ac69f1984`

Mind rebuilding from git, and maybe double checking you don't have any old versions of msgpack in unexpected places?

thanks!

**Comment by Sean-Der** [comment]
Close this for now @ecyuan feel free to reopen if this is still an issue, thanks!
