### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by casterx** [msgpack/msgpack-php#74]
Hi all,

Is this extension compatible to PHP 7? Does it need to be fixed or ready for PHP 7? If it needs to be fixed, do you manage to do it? and ETA?

Thanks

**Comment by Sean-Der** [comment]
Hi @casterx 

There is a [PHP 7 Branch](https://github.com/msgpack/msgpack-php/tree/php7), also if you install from [PECL](https://pecl.php.net/package/msgpack) version 2.0.0 is PHP 7 compatible.

thanks
