### ISSUE TITLE
msgpack_pack 的行为在PHP5与PHP7中的行为不一致的Bug

### ISSUE THREAD

**Issue by imiskolee** [msgpack/msgpack-php#76]
我使用了一段相同的代码在PHP5.5.23的环境下与PHP 7.0.0的环境下进行运行，得到的结果不一致，完整的测试代码如下：

``` PHP
<?php

$media_id = "MGr4RH54AulISsTl6yNQeI8HIRpedncWzY_H-jwbYM0vCeuLxoAgtkMsw10EqEY-";

 $query = array(

            'media_id'  => $media_id

        );

 $config = array(

            'formatter' => 'binary'

);

$data = array(
    "wxd1ea5bd588c978f4",
    "wxa4d8ba64ab6b8178",
    "API_MEDIA_GET",
    $query,
    $config
);

$pack = array(
    "i" => 123123,
    "m" => "mp_get",
    "p" => $data
);

$body = msgpack_pack($pack);

for($i=0;$i<strlen($body);$i++){

        echo ord($body[$i])."\n";

}
```

PHP5中的运行结果如下：

131
161
105
206
0
1
224
243
161
109
166
109
112
95
103
101
116
161
112
149
178
119
120
100
49
101
97
53
98
100
53
56
56
99
57
55
56
102
52
178
119
120
97
52
100
56
98
97
54
52
97
98
54
98
56
49
55
56
173
65
80
73
95
77
69
68
73
65
95
71
69
84
129
168
109
101
100
105
97
95
105
100
218
0
64
77
71
114
52
82
72
53
52
65
117
108
73
83
115
84
108
54
121
78
81
101
73
56
72
73
82
112
101
100
110
99
87
122
89
95
72
45
106
119
98
89
77
48
118
67
101
117
76
120
111
65
103
116
107
77
115
119
49
48
69
113
69
89
45
129
169
102
111
114
109
97
116
116
101
114
166
98
105
110
97
114
121

PHP7中的运行结果如下：

131
161
105
206
0
1
224
243
161
109
166
109
112
95
103
101
116
161
112
149
178
119
120
100
49
101
97
53
98
100
53
56
56
99
57
55
56
102
52
178
119
120
97
52
100
56
98
97
54
52
97
98
54
98
56
49
55
56
173
65
80
73
95
77
69
68
73
65
95
71
69
84
129
168
109
101
100
105
97
95
105
100
217
64
77
71
114
52
82
72
53
52
65
117
108
73
83
115
84
108
54
121
78
81
101
73
56
72
73
82
112
101
100
110
99
87
122
89
95
72
45
106
119
98
89
77
48
118
67
101
117
76
120
111
65
103
116
107
77
115
119
49
48
69
113
69
89
45
129
169
102
111
114
109
97
116
116
101
114
166
98
105
110
97
114
121

**Comment by laruence** [comment]
如果你反序列化后的结果是对的, 就没问题... 不同版本间是有可能有些许差异.

**Comment by imiskolee** [comment]
Msgpack版本：

PHP5中：

msgpack

MessagePack Support => enabled
Session Support => enabled
extension Version => 0.5.5
header Version => 0.5.4


PHP7中：

?msgpack\.
MessagePack Support => enabled
Session Support => enabled
extension Version => 2.0.1-dev
header Version => 0.5.4

**Comment by imiskolee** [comment]
现在这个问题出现在Yar中，在PHP7中调用PHP5中的YarServer在某些参数的情况下，会触发一个yar异常：Fatal error: Uncaught Yar_Server_Exception: need specifical request method 

然后跟踪到了msgpack里面的差异，

**Comment by imiskolee** [comment]
之前有实现一个Yar Protocol的调试器：
```PHP
<?php
/**
 * Use CURL For PHP implement  yar client.
 *
 */
$media_id = "MGr4RH54AulISsTl6yNQeI8HIRpedncWzY_H-jwbYM0vCeuLxoAgtkMsw10EqEY-";
 $query = array(

            'media_id'  => $media_id

        );

        $config = array(

            'formatter' => 'binary'
        );

$params = array(
'wxd1ea5bd588c978f4',
'wxa4d8ba64ab6b8178',
'API_MEDIA_GET',
$query,$config
);
$params_str = json_encode($params);
//create request body
$body = '{"i":123123,"m":"mp_get","p":'.$params_str.'}';

$body = json_decode($body,true);

$body = msgpack_pack($body);

for($i=0;$i<strlen($body);$i++){

        echo ord($body[$i])."\n";

}


$f = fopen("/tmp/protocol.log","a+");

fwrite($f,$body);

fclose($f);

//Create Yar Header protocol,about pack rule,more see:http://php.net/manual/zh/function.pack.php

$format = "I1S1I1I1C32C32I1";   // 82bit

$pack = pack($format,123123,0,1626136448,0,
    '','','','','','','','','','',
    '','','','','','','','','','',
    '','','','','','','','','','',
    '','',
    '','','','','','','','','','',
    '','','','','','','','','','',
    '','','','','','','','','','',
    '','', strlen($body)
);

//Create Package Protocol
$format = "a8";     //8 bit
$packager_pack = pack($format,'msgpack');

$protocol_data = $pack.$packager_pack.$body;

$uri = "http://wechat-proxy.service-php.weixinhost.com";
$ch = curl_init ();
curl_setopt ( $ch, CURLOPT_URL, $uri );
curl_setopt ( $ch, CURLOPT_POST, 1 );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, 1 );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $protocol_data );
$return = curl_exec ( $ch );

var_dump($return);
$content = substr($return,82 + 8,strlen($return));

$content = json_decode($content,true);


if($content['e']){      //Exception

    throw new Exception($content['e']);

}

if($content['o']){      //Output

    echo $content['o'];

}

$data = $content['r'];          //Return

var_dump($content);
```

这段代码也会和Yar_Client在PHP7中报异常：Uncaught Yar_Server_Exception: need specifical request method

**Comment by imiskolee** [comment]
暂时，将php5中的msgpack从0.5.7 升级到0.5.8-dev(branch master)，解决了该问题。
