### ISSUE TITLE
php_msgpack.h  line 4  can not found  ext/standard/php_smart_str.h

### ISSUE THREAD

**Issue by quqiufeng** [msgpack/msgpack-php#78]
just find a  php_smart_string.h file in source code of php7

**Comment by maurorappa** [comment]
~/php-7.0.3# find . |grep php_smart_str.h
gives no results...

**Comment by Sean-Der** [comment]
Hey @quqiufeng and @maurorappa 

To use msgpack with PHP 7 please use the https://github.com/msgpack/msgpack-php/tree/php7 branch. If that works out for you, can you please close this issue? If not feel free to follow up with anymore questions.

thanks

**Comment by maurorappa** [comment]
Thanks Sean for the reply! 
I noticed the PHP7 version after I wrote here... 
just put a disclaimer in the welcome page ;)

**Comment by bigbes** [comment]
Why are you using `<Zend/zend_smart_str.h>` and not `<ext/standard/php_smart_string.h>` in PHP7?

**Comment by laruence** [comment]
bigbes, smart_str result zend_string, php_smart_string result char *

**Comment by bigbes** [comment]
@laruence thank you.

**Comment by Sean-Der** [comment]
Hi @maurorappa 
PHP 7 is now on the master branch, so should be less confusing now!

Hopefully this makes it easier on everyone, thanks.
