### ISSUE TITLE
Serialize issue

### ISSUE THREAD

**Issue by rlalak** [msgpack/msgpack-php#80]
I found issue in serialize function. When I try to serialize object with unseted field I got the error:
`[msgpack] (msgpack_serialize_zval) type is unsupported, encoded as null`

Example code:
```
class MyClass
{
  protected $field;

  public function preSerialize()
  {
    unset($this->field);
  }
}

$t = new MyClass();
$t->preSerialize();
msgpack_serialize($t);
```
PHP Version 7.0.3
msgpack version 2.0.0 (header version 0.5.4)

**Comment by laruence** [comment]
it should be fixed, thanks for the reporting :)

**Comment by rlalak** [comment]
It work now :)
but I report new issue: https://github.com/msgpack/msgpack-php/issues/81
