### ISSUE TITLE
msgpack_unpack is super slow (30x times igbinary) on big data sets

### ISSUE THREAD

**Issue by parf** [msgpack/msgpack-php#90]
msgpack_unpack is super slow (30x times igbinary) on big data sets
In this example 1500x1500 array unpacking take 90 seconds !!! (only 34MB of data)
i can gzip this data in 0.1 sec

https://gist.github.com/parf/f05ca955a523657581b55c62fc982059

> ./igbinary-vs-msgpack.php 
> PHP Version: 5.6.20 @  
> Data set: `array 1500 x 1500`, performed 2 iterations, data-set-memory-usage: 1,306.0M  
> ALGO                   SIZE-RAW    UNPACK1/sec PACK1/sec  << time per one iteration
> igbinary_serialize:  34,866,787     **1.8**     2.1
> msgpack_pack:        34,348,503   **51.9**     1.3
> 
> ./igbinary-vs-msgpack.php 
> PHP Version: 7.0.8 @
> Data set: `array 1500 x 1500`, performed 2 iterations, data-set-memory-usage: 1,101.0M
> ALGO                   SIZE-RAW    UNPACK1/sec PACK1/sec  << time per one iteration
> igbinary_serialize:  34,866,787     **3.3**     0.63
> msgpack_pack:        34,348,503   **91.5**     1.6

**Comment by rybakit** [comment]
Looks like it's even slower than pure php implementation. I've benchmarked [msgpack.php](https://github.com/rybakit/msgpack.php) vs pecl extension with 1500x1500 array and got this:

```
$ php tests/bench_big_array.php
empty_loop         0.000
pecl             119.660    119.660
pure              26.962    26.962
------------------------
Total            146.622
```

```
$ php -v
PHP 7.0.5 (cli) (built: Apr 23 2016 10:48:01) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

https://gist.github.com/rybakit/59467489f2c424726b9411968b5b3b7a

**Comment by rybakit** [comment]
I slightly updated my benchmark to test packing/unpacking separately + add a test for `MessagePackUnpacker`: https://gist.github.com/rybakit/59467489f2c424726b9411968b5b3b7a#file-bench_big_array2-php

So, packing performs well compared to unpacking:
```
$ php tests/bench_big_array.php
empty_loop         0.000
pecl_pack          1.594    1.594
pecl_unpack      103.036    103.036
pecl_unpack_buf   90.596    90.596
pure_pack          6.363    6.363
pure_unpack        5.042    5.042
------------------------
Total            206.632
```
