### ISSUE TITLE
fatal error: Zend/zend_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by jockchou** [msgpack/msgpack-php#98]
In file included from /usr/local/src/msgpack-php/msgpack.c:16:0:
/usr/local/src/msgpack-php/php_msgpack.h:4:56: fatal error: Zend/zend_smart_str.h: No such file or directory
 #include "Zend/zend_smart_str.h" /* for smart_string */

**Comment by stamster** [comment]
This lib is present only in PHP7. 
Master branch here does not seem to support anything but PHP 7.x.

Refer to: #97

**Comment by stamster** [comment]
This version will work: https://github.com/msgpack/msgpack-php/archive/msgpack-0.5.7.tar.gz

**Comment by stamster** [comment]
#101
