### ISSUE TITLE
php 7.2 fail

### ISSUE THREAD

**Issue by xianhuawei** [msgpack/msgpack-php#99]
config.status: creating config.h
running: make
/bin/sh /tmp/pear/temp/pear-build-rootP5usKh/msgpack-2.0.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/msgpack -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootP5usKh/msgpack-2.0.1/include -I/tmp/pear/temp/pear-build-rootP5usKh/msgpack-2.0.1/main -I/tmp/pear/temp/msgpack -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/msgpack/msgpack.c -o msgpack.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/msgpack -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootP5usKh/msgpack-2.0.1/include -I/tmp/pear/temp/pear-build-rootP5usKh/msgpack-2.0.1/main -I/tmp/pear/temp/msgpack -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/msgpack/msgpack.c  -fPIC -DPIC -o .libs/msgpack.o
/tmp/pear/temp/msgpack/msgpack.c: In function ‘ps_srlzr_decode_msgpack’:
/tmp/pear/temp/msgpack/msgpack.c:160:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^
/tmp/pear/temp/msgpack/msgpack.c: In function ‘php_msgpack_unserialize’:
/tmp/pear/temp/msgpack/msgpack.c:210:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^
make: **\* [msgpack.lo] Error 1
ERROR: `make' failed

**Comment by sodabrew** [comment]
A proposed fix is posted in #100.

**Comment by Sean-Der** [comment]
Hey @xianhuawei sorry this took so long, a fix was merged into master would you mind trying it? Feel free to reopen if you are still having issues, thanks!
